### ISSUE TITLE
Unconfig generate one error

### ISSUE THREAD

**Issue by GusMuche** [aficustree/homebridge-sss-platform#10]
I've try this plugin and it really work great.

But...

After delete the configuration for this plugin on my test homebridge (inside the config.json), I've this error :

```
[4/25/2020, 7:32:18 PM] TypeError: Cannot read property 'hasOwnProperty' of null
    at new SSSPlatform (/homebridge/node_modules/homebridge-sss-platform/index.js:89:40)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
```

So it happens after emptying the `config.json` from configuration of this plugin.

Solution : delete all the `accessories` and `persist` files from the directories.

If I put the config again, it work normally.

**Comment by aficustree** [comment]
you can't just remove the plugin from the config.json, you actually have to uninstall it using npm like `npm uninstall home bridge-sss-platform`, maybe with the `-g` flag depending on how you installed

**Comment by GusMuche** [comment]
Ok, it's quite a bit strange that if we use the plugin we need to delete them after that.

Maybe you can try to detect that no config has be done and stopping the plugin.

```
if (!config) {
      this.log.warn(`Ignoring SSs plugin  setup because it is not configured`);
      return;
}
```

**Comment by aficustree** [comment]
seems to be fixed by [this homebridge issue](https://github.com/homebridge/homebridge/pull/2481)
